Documenten/SmoothBoardStylers/SmoothBoardStylersAppKt3Kt4/Models/Voorraad.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmoothBoardStylersApp.Models
{
    public class Voorraad
    {
        [ForeignKey("Surfboard")]
        [Display(Name = "Surfboard")]
        public int SurfboardId { get; set; }

        public virtual Surfboard Surfboard { get; set; }

        [ForeignKey("Filiaal")]
        [Display(Name = "Filiaal")]
        public int FiliaalId { get; set; }

        public virtual Filiaal Filiaal { get; set;  }

        public int Aantal { get; set; }
    }
}

Documenten/SmoothBoardStylers/SmoothBoardStylersAppKt3Kt4/Components/VoorraadViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmoothBoardStylersApp.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmoothBoardStylersApp.Components
{
    public class VoorraadViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public VoorraadViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Toont de voorraad van Surfboards in een Filiaal
        /// </summary>
        /// <param name="id">het Id van het Filiaal</param>
        /// <returns>ViewComponentView met een overzicht van de voorraad</returns>
        public async Task<IViewComponentResult> InvokeAsync(int? id)
        {
            var surfboards = await _context.Voorraad
                .Include(v => v.Filiaal)
                .Include(v => v.Surfboard)
                .Where(v => v.Aantal > 0)
                .OrderBy(v => v.Surfboard.Naam)
                .ToListAsync();

            if (id != null && id != 0)
            {
                var filiaal = await _context.Filialen.FindAsync(id);
                if (filiaal != null)
                {
                    surfboards = surfboards
                        .Where(v => v.FiliaalId == id)
                        .ToList();
                }
            }
            return View(surfboards);
        }
    }
}

Documenten/SmoothBoardStylers/SmoothBoardStylersAppKt3Kt4/Controllers/VoorraadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmoothBoardStylersApp.Data;
using SmoothBoardStylersApp.Models;

namespace SmoothBoardStylersApp.Controllers
{
    [Authorize]
    public class VoorraadController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VoorraadController(ApplicationDbContext context)
        {
            _context = context;
        }

        private Filiaal GeenFiliaal => new Filiaal { Id = 0, Naam = "Alle Filialen" };

        private async Task<List<Filiaal>> FilialenKeuzes()
        {
            var filialen = await _context.Filialen
                .OrderBy(f => f.Naam)
                .ToListAsync();

            filialen.Insert(0, GeenFiliaal);
            return filialen;
        }

        // GET: Voorraad
        public async Task<IActionResult> Index()
        {
            var filiaal = GeenFiliaal;

            var filialen = await FilialenKeuzes();
            ViewData["FiliaalId"] = new SelectList(filialen, "Id", "Naam");
            return View(filiaal);
        }

        [HttpPost]
        public async Task<IActionResult> Index(int filiaal)
        {
            var selectie = await _context.Filialen.FindAsync(filiaal);
            if (selectie == null)
            {
                selectie = GeenFiliaal;
            }
            var filialen = await FilialenKeuzes();
            ViewData["FiliaalId"] = new SelectList(filialen, "Id", "Naam", selectie.Id);
            return View(selectie);
        }

        private List<Surfboard> SurfboardsNietInVoorraad(int id)
        {
            var surfboards = _context.Surfboards
                .OrderBy(s => s.Naam)
                .ToList();

            if (id == 0)
            {
                return surfboards;
            }

            var surfboardsInVoorraad = _context.Voorraad
               .Include(v => v.Surfboard)
               .Where(v => v.FiliaalId == id && v.Aantal > 0)
               .Select(v => v.Surfboard)
               .ToList();

            surfboards = surfboards
                .Except(surfboardsInVoorraad)
                .ToList();

            return surfboards;
        }

        // GET: Voorraad/Create
        public async Task<IActionResult> Create(int? id)
        {
            var filiaal = await _context.Filialen.FindAsync(id);

            if (filiaal == null)
            {
                filiaal = new Filiaal { Id = 0 };
            }
            var surfboards = SurfboardsNietInVoorraad(filiaal.Id);

            var voorraad = new Voorraad { FiliaalId = filiaal.Id };
            ViewData["FiliaalId"] = new SelectList(_context.Filialen, "Id", "Naam", filiaal.Id);
            ViewData["SurfboardId"] = new SelectList(surfboards, "Id", "Naam");
            return View(voorraad);
        }

        // POST: Voorraad/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SurfboardId,FiliaalId,Aantal")] Voorraad voorraad)
        {
            if (ModelState.IsValid)
            {

                var bestaandeVoorraad = await _context.Voorraad.FindAsync(voorraad.SurfboardId, voorraad.FiliaalId);
                if (bestaandeVoorraad == null)
                {
                    try
                    {
                        _context.Add(voorraad);
                        await _context.SaveChangesAsync();
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex.Message);                        
                    }
                }
                else
                {
                    bestaandeVoorraad.Aantal += voorraad.Aantal; 
                    _context.Update(bestaandeVoorraad);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index), new { Id = voorraad.FiliaalId });
            }

            var surfboards = SurfboardsNietInVoorraad(voorraad.FiliaalId);
            ViewData["FiliaalId"] = new SelectList(_context.Filialen, "Id", "Naam", voorraad.FiliaalId);
            ViewData["SurfboardId"] = new SelectList(surfboards, "Id", "Naam", voorraad.SurfboardId);
            return View(voorraad);
        }

        // GET: Voorraad/Edit/5
        public async Task<IActionResult> Edit(int surfboardId, int filiaalId)
        {
            var voorraad = await _context.Voorraad
                .Include(v => v.Filiaal)
                .Include(v => v.Surfboard)
                .FirstOrDefaultAsync(v => v.SurfboardId == surfboardId && v.FiliaalId == filiaalId);
            if (voorraad == null)
            {
                return NotFound();
            }
            return View(voorraad);
        }

        // POST: Voorraad/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Voorraad voorraad)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(voorraad);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    Console.WriteLine(ex.Message);
                }
                return RedirectToAction(nameof(Index), new { Id = voorraad.FiliaalId });
            }

            return View(voorraad);
        }

        // GET: Voorraad/Delete/5
        public async Task<IActionResult> Delete(int surfboardId, int filiaalId)
        {
            var voorraad = await _context.Voorraad.FindAsync(new { surfboardId, filiaalId });

            if (voorraad == null)
            {            
                return NotFound();
            }

            voorraad.Aantal = 0;
            try
            {
                _context.Update(voorraad);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException ex)
            {
                Console.WriteLine(ex.Message);
            }

            return View(voorraad);
        }
    }
}

Documenten/SmoothBoardStylers/SmoothBoardStylersAppKt3Kt4/Views/Voorraad/Create.cshtml
@model SmoothBoardStylersApp.Models.Voorraad

@{
    ViewData["Title"] = "Voorraad";
}

<h1>Create</h1>

<h4>Voorraad</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SurfboardId" class="control-label"></label>
                <select asp-for="SurfboardId" class ="form-control" asp-items="ViewBag.SurfboardId"></select>
            </div>
            <div class="form-group">
                <label asp-for="FiliaalId" class="control-label"></label>
                <select asp-for="FiliaalId" class ="form-control" asp-items="ViewBag.FiliaalId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Aantal" class="control-label"></label>
                <input asp-for="Aantal" class="form-control" />
                <span asp-validation-for="Aantal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Documenten/SmoothBoardStylers/SmoothBoardStylersAppKt3Kt4/Views/Voorraad/Delete.cshtml
@model SmoothBoardStylersApp.Models.Voorraad

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Voorraad</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surfboard)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surfboard.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Filiaal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Filiaal.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aantal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aantal)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SurfboardId" />
        <input type="hidden" asp-for="FiliaalId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Documenten/SmoothBoardStylers/SmoothBoardStylersAppKt3Kt4/Views/Voorraad/Details.cshtml
@model SmoothBoardStylersApp.Models.Voorraad

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Voorraad</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surfboard)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surfboard.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Filiaal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Filiaal.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aantal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aantal)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Documenten/SmoothBoardStylers/SmoothBoardStylersAppKt3Kt4/Views/Voorraad/Edit.cshtml
@model SmoothBoardStylersApp.Models.Voorraad

@{
    ViewData["Title"] = "Voorraad";
}

<h1>Edit</h1>

<h4>Voorraad</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SurfboardId" />
            <input type="hidden" asp-for="FiliaalId" />
            <div class="form-group">
                <label asp-for="Filiaal" class="control-label"></label>
                <input type="text" value="@Model.Filiaal.Naam" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="Surfboard" class="control-label"></label>
                <input type="text" value="@Model.Surfboard.Naam" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="Aantal" class="control-label"></label>
                <input asp-for="Aantal" class="form-control" />
                <span asp-validation-for="Aantal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Documenten/SmoothBoardStylers/SmoothBoardStylersAppKt3Kt4/Views/Voorraad/Index.cshtml
@model SmoothBoardStylersApp.Models.Filiaal

@{
    ViewData["Title"] = "Index";
    ViewData["Id"] = Model.Id;
    ViewData["Filiaal"] = Model.Naam;
}

<h1>Voorraad</h1>

<div class="row text-center">
    <form asp-action="Index">
        <label for="filiaal">Selecteer Filiaal: </label>
        <select name="filiaal" id="filiaal" asp-items="ViewBag.FiliaalId"></select>
        <input type="submit" value="selecteer" />
    </form>
</div>


@await Component.InvokeAsync("Voorraad", new { id = Model.Id })