Documenten/SmoothBoardStylers/SmoothBoardStylersAppKt3Kt4/Controllers/FaqsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmoothBoardStylersApp.Data;
using SmoothBoardStylersApp.Models;
using System.Linq;
using System.Threading.Tasks;

namespace SmoothBoardStylersApp.Controllers
{
    [Authorize]
    public class FaqsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FaqsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Faqs
        public async Task<IActionResult> Index()
        {
            var aantalVragen = _context.Vragen.Count();
            if (aantalVragen > 0)
            {
                ViewData["AantalVragen"] = $"{aantalVragen} vragen zijn nog niet beantwoord.";
            }
            return View(await _context.Faqs.ToListAsync());
        }

        [AllowAnonymous]
        public async Task<IActionResult> Faq()
        {
            return View(await _context.Faqs.ToListAsync());
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Faq(string vraag, string email)
        {
            if (!string.IsNullOrEmpty(email) && !string.IsNullOrEmpty(vraag))
            {
                email = email.ToLower();
                var contact = await _context.Contacten
                    .FirstOrDefaultAsync(c => c.EmailAdres == email);

                if (contact == null)
                {
                    contact = new Contact
                    {
                        EmailAdres = email
                    };
                    _context.Add(contact);
                    await _context.SaveChangesAsync();
                }

                var nieuweVraag = new Vraag { Tekst = vraag, VraagstellerId = contact.Id };
                _context.Add(nieuweVraag);
                await _context.SaveChangesAsync();
                ViewData["Message"] = "Dank je wel voor je vraag. We beantwoorden hem zo snel mogelijk.";
                return await Faq();
            }
            return RedirectToAction(nameof(Faq));
        }

        // GET: Faqs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Faqs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Vraag,Antwoord")] Faq faq)
        {
            if (ModelState.IsValid)
            {
                _context.Add(faq);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(faq);
        }

        // GET: Faqs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var faq = await _context.Faqs.FindAsync(id);
            if (faq == null)
            {
                return NotFound();
            }
            return View(faq);
        }

        // POST: Faqs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Vraag,Antwoord")] Faq faq)
        {
            if (id != faq.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(faq);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FaqExists(faq.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(faq);
        }

        // GET: Faqs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var faq = await _context.Faqs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (faq == null)
            {
                return NotFound();
            }

            return View(faq);
        }

        // POST: Faqs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var faq = await _context.Faqs.FindAsync(id);
            _context.Faqs.Remove(faq);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }        

        private bool FaqExists(int id)
        {
            return _context.Faqs.Any(e => e.Id == id);
        }
    }
}

Documenten/SmoothBoardStylers/SmoothBoardStylersAppKt3Kt4/Controllers/FilialenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmoothBoardStylersApp.Data;
using SmoothBoardStylersApp.Models;

namespace SmoothBoardStylersApp.Controllers
{
    [Authorize]
    public class FilialenController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FilialenController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Filialen
        public async Task<IActionResult> Index()
        {
            return View(await _context.Filialen.ToListAsync());
        }

        // GET: Filialen/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filiaal = await _context.Filialen
                .FirstOrDefaultAsync(m => m.Id == id);
            if (filiaal == null)
            {
                return NotFound();
            }

            return View(filiaal);
        }

        // GET: Filialen/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Filialen/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create ([Bind("Id,Naam,Adres,Woonplaats")] Filiaal filiaal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(filiaal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(filiaal);
        }

        // GET: Filialen/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filiaal = await _context.Filialen.FindAsync(id);
            if (filiaal == null)
            {
                return NotFound();
            }
            return View(filiaal);
        }

        // POST: Filialen/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naam,Adres,Woonplaats")] Filiaal filiaal)
        {
            if (id != filiaal.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(filiaal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FiliaalExists(filiaal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(filiaal);
        }

        // GET: Filialen/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filiaal = await _context.Filialen
                .FirstOrDefaultAsync(m => m.Id == id);
            if (filiaal == null)
            {
                return NotFound();
            }

            return View(filiaal);
        }

        // POST: Filialen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var filiaal = await _context.Filialen.FindAsync(id);
            _context.Filialen.Remove(filiaal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FiliaalExists(int id)
        {
            return _context.Filialen.Any(e => e.Id == id);
        }
    }
}

Documenten/SmoothBoardStylers/SmoothBoardStylersAppKt3Kt4/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmoothBoardStylersApp.Data;
using SmoothBoardStylersApp.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace SmoothBoardStylersApp.Controllers
{
    public class ShopController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ShopController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var surfboards = await _context.Surfboards
                .Include(s => s.Materiaal)
                .OrderBy(s => s.Naam)
                .ToListAsync(); ;
            return View(surfboards);
        }

        public async Task<IActionResult> Board(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var surfboard = await _context.Surfboards
                .Include(s => s.Materiaal)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (surfboard == null)
            {
                return NotFound();
            }

            return View(surfboard);
        }

        [HttpPost]
        public async Task<IActionResult> Interesse(int? id, string email)
        {

            if (id == null)
            {
                return NotFound();
            }

            var surfboard = await _context.Surfboards
                .FindAsync(id);

            if (surfboard == null)
            {
                return NotFound();
            }

            if (! string.IsNullOrEmpty(email))
            {
                email = email.ToLower();
                var contact = await _context.Contacten
                    .FirstOrDefaultAsync(c => c.EmailAdres == email);

                if (contact == null)
                {
                    contact = new Contact
                    {
                        EmailAdres = email
                    };
                    _context.Add(contact);
                    await _context.SaveChangesAsync();
                }
                
                await _context.Entry(contact).Collection(c => c.SurfBoardInteresses).LoadAsync();

                if (contact.SurfBoardInteresses.FirstOrDefault(s => s.Id == id) == null)
                {
                    contact.SurfBoardInteresses.Add(surfboard);
                    try
                    {
                        _context.Update(contact);
                        await _context.SaveChangesAsync();
                    }
                    catch (Exception ex)
                    {
                        System.Console.WriteLine(ex.Message);
                        return NotFound();
                    }
                }
                ViewData["Message"] = $"Dank je wel voor je interesse in {surfboard.Naam}";

            }

            return View("Board", surfboard);
        }
    }
}

Documenten/SmoothBoardStylers/SmoothBoardStylersAppKt3Kt4/Controllers/VragenController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmoothBoardStylersApp.Data;
using System.Threading.Tasks;

namespace SmoothBoardStylersApp.Controllers
{
    public class VragenController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VragenController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Vragens
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Vragen.Include(v => v.Vraagsteller);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Vragens/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var vraag = await _context.Vragen.FindAsync(id);
            _context.Vragen.Remove(vraag);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Documenten/SmoothBoardStylers/SmoothBoardStylersAppKt3Kt4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="nl-nl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmoothBoard Stylers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SmoothBoard Stylers</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Index">Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faqs" asp-action="Faq">F.A.Q.</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark dropdown-toggle" href="#" data-toggle="dropdown">Admin</a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Voorraad" asp-action="Index">Voorraad</a>
                                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Surfboards" asp-action="Index">Surfboards</a>
                                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Materialen" asp-action="Index">Materialen</a>
                                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Filialen" asp-action="Index">Filialen</a>
                                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Faqs" asp-action="Index">F.A.Q.</a>
                                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Vragen" asp-action="Index">Vragen</a>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - @DateTime.Today.Year - Horizon College
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>